version:           '2'

services:
  plex:
    image:         plexinc/pms-docker:latest

    restart:       on-failure
    cpu_shares:    1024
    cpuset:        0,1,2

    mem_limit:     1g
    memswap_limit: 2g
    privileged:    true

    network_mode:  host

    networks:
      - web
    ports:
      - 32400:32400
      - 32469:32469
      - 1900:1900/udp
    environment:
      - PLEX_CLAIM="${PLEX_TOKEN}"
      - ADVERTISE_IP="https://plex.${DOMAIN_NAME}/"
      - PLEX_UID=${USER_ID}
      - PLEX_GID=${GROUP_ID}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /mnt/public/Movies:/data/movies
      - /mnt/public/Shows:/data/tvshows
      - /mnt/public/Photos:/data/photos
      - /mnt/public/Music:/data/music
      - ./config/plex-config/:/config
      - /tmp/transcode/:/transcode
